travail/mission/src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;

#[Gedmo\SoftDeleteable(fieldName: "deletedAt")]
#[ORM\Entity(repositoryClass: ProjectRepository::class)]
class Project
{
    use SoftDeleteableEntity;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(max: 255)]
    #[Assert\NotBlank]
    private ?string $title = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    #[Assert\LessThan(
        propertyPath: "deadline", 
        message: "La date de début doit être antérieure à la date limite.")]
    private ?\DateTime $startDate = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTime $deadline = null;

    /**
     * @var Collection<int, Task>
     */
    #[ORM\OneToMany(targetEntity: Task::class, mappedBy: 'project', orphanRemoval: true)]
    private Collection $tasks;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'projects')]
    private Collection $users;

    /**
     * @var Collection<int, Tag>
     */
    #[ORM\ManyToMany(targetEntity: Tag::class, mappedBy: 'projects')]
    private Collection $tags;

    public function __construct()
    {
        $this->tasks = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getStartDate(): ?\DateTime
    {
        return $this->startDate;
    }

    public function setStartDate(?\DateTime $startDate): static
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getDeadline(): ?\DateTime
    {
        return $this->deadline;
    }

    public function setDeadline(?\DateTime $deadline): static
    {
        $this->deadline = $deadline;

        return $this;
    }

    /**
     * @return Collection<int, Task>
     */
    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function addTask(Task $task): static
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks->add($task);
            $task->setProject($this);
        }

        return $this;
    }

    public function removeTask(Task $task): static
    {
        if ($this->tasks->removeElement($task)) {
            // set the owning side to null (unless already changed)
            if ($task->getProject() === $this) {
                $task->setProject(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addProject($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            $user->removeProject($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Tag>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): static
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
            $tag->addProject($this);
        }

        return $this;
    }

    public function removeTag(Tag $tag): static
    {
        if ($this->tags->removeElement($tag)) {
            $tag->removeProject($this);
        }

        return $this;
    }
}

travail/mission/src/Entity/User.php
<?php

namespace App\Entity;

use App\Enum\ContractEnum;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use DateTime;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(max: 255)]
    #[Assert\NotBlank]
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(max: 255)]
    #[Assert\NotBlank]
    private ?string $lastName = null;

    #[ORM\Column(length: 255, unique: true)]
    #[Assert\Length(max: 255)]
    #[Assert\NotBlank]
    #[Assert\Email]
    private ?string $email = null;

    #[ORM\Column]
    private bool $isActive = true;

    #[ORM\Column(length: 255)]
    #[Assert\Length(max: 255)]
    private ?string $role = null;

    #[ORM\Column]
    private ?DateTime $hiredOn = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(max: 255)]
    #[Assert\NotBlank]
    private ?string $password = null;


    #[ORM\Column(length: 255)]
    #[Assert\Length(max: 255)]
    #[Assert\NotBlank]
    #[Assert\Choice(callback: 'App\\Enum\\ContractEnum::values')]
    private ?string $status = null;

    /**
     * @var Collection<int, Project>
     */
    #[ORM\ManyToMany(targetEntity: Project::class, inversedBy: 'users')]
    private Collection $projects;

    /**
     * @var Collection<int, TimeSlot>
     */
    #[ORM\OneToMany(targetEntity: TimeSlot::class, mappedBy: 'worker', orphanRemoval: true)]
    private Collection $timeSlots;

    /**
     * @var Collection<int, Task>
     */
    #[ORM\ManyToMany(targetEntity: Task::class, inversedBy: 'users')]
    private Collection $tasks;

    public function __construct()
    {
        $this->projects = new ArrayCollection();
        $this->timeSlots = new ArrayCollection();
        $this->tasks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): static
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): static
    {
        $this->role = $role;

        return $this;
    }

    public function getHiredOn(): ?DateTime
    {
        return $this->hiredOn;
    }

    public function setHiredOn(DateTime $hiredOn): static
    {
        $this->hiredOn = $hiredOn;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getStatus(): ?ContractEnum
    {
        return $this->status ? ContractEnum::tryFrom($this->status) : null;
    }

    public function setStatus(?ContractEnum $status): static
    {
        $this->status = $status?->value;

        return $this;
    }

    /**
     * @return Collection<int, Project>
     */
    public function getProjects(): Collection
    {
        return $this->projects;
    }

    public function addProject(Project $project): static
    {
        if (!$this->projects->contains($project)) {
            $this->projects->add($project);
        }

        return $this;
    }

    public function removeProject(Project $project): static
    {
        $this->projects->removeElement($project);

        return $this;
    }

    /**
     * @return Collection<int, TimeSlot>
     */
    public function getTimeSlots(): Collection
    {
        return $this->timeSlots;
    }

    public function addTimeSlot(TimeSlot $timeSlot): static
    {
        if (!$this->timeSlots->contains($timeSlot)) {
            $this->timeSlots->add($timeSlot);
            $timeSlot->setWorker($this);
        }

        return $this;
    }

    public function removeTimeSlot(TimeSlot $timeSlot): static
    {
        if ($this->timeSlots->removeElement($timeSlot)) {
            // set the owning side to null (unless already changed)
            if ($timeSlot->getWorker() === $this) {
                $timeSlot->setWorker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Task>
     */
    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function addTask(Task $task): static
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks->add($task);
        }

        return $this;
    }

    public function removeTask(Task $task): static
    {
        $this->tasks->removeElement($task);

        return $this;
    }

    public function __toString(): string
    {
        return $this->firstName . ' ' . $this->lastName;
    }

    public function getInitials(): string
    {
        $first = $this->firstName ? mb_substr($this->firstName, 0, 1) : '';
        $last = $this->lastName ? mb_substr($this->lastName, 0, 1) : '';

        return mb_strtoupper($first . $last);
    }
}

travail/mission/src/Form/ProjectType.php
<?php

namespace App\Form;

use App\Entity\Project;
use App\Entity\Tag;
use App\Entity\User;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Titre du projet',
            ])
            ->add('users', EntityType::class, [
                'label' => 'Inviter des membres',
                'class' => User::class,
                'choice_label' => fn(User $user) => $user,
                'multiple' => true,
                'by_reference' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
        ]);
    }
}

travail/mission/src/Controller/ProjectController.php
<?php

namespace App\Controller;

use App\Entity\Project;
use App\Enum\TaskCategoryEnum;
use App\Form\ProjectType;
use App\Repository\ProjectRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Repository\TaskRepository;

#[Route('/')]
#[Route('/project')]
final class ProjectController extends AbstractController
{
    #[Route(name: 'app_project_index', methods: ['GET'])]
    public function index(ProjectRepository $projectRepository): Response
    {
        return $this->render('project/projects.html.twig', [
            'projects' => $projectRepository->findAll(),
        ]);
    }

    #[Route('/{id}/show', name: 'app_project_show', methods: ['GET'])]
    public function show(Project $project, TaskRepository $taskRepository): Response
    {
        $categories = [];
        foreach (TaskCategoryEnum::cases() as $categoryName) {
            $tasksInCategory = $taskRepository->findAllByCategoryProject($categoryName->value, $project);
            $categories[] = [
                'name' => $categoryName->value,
                'tasks' => $tasksInCategory
            ];
        }
        return $this->render('project/show.html.twig', [
            'project' => $project,
            'categories' => $categories,
        ]);
    }

    #[Route('/new', name: 'app_project_new', methods: ['GET', 'POST'])]
    #[Route('/{id}/edit', name: 'app_project_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ?Project $project = null, EntityManagerInterface $entityManager): Response
    {
        if ($project === null) {
            $project = new Project();
        }
        $form = $this->createForm(ProjectType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($project);
            $entityManager->flush();

            return $this->redirectToRoute('app_project_show', [
                'id' => $project->getId(),
            ], Response::HTTP_SEE_OTHER);
        }

        return $this->render('project/edit.html.twig', [
            'project' => $project,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: 'app_project_delete', methods: ['POST'])]
    public function delete(Request $request, Project $project, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$project->getId(), $request->request->get('_token'))) {
            try {
                $entityManager->remove($project);
                $entityManager->flush();

                $this->addFlash('success', 'Projet supprimé.');
            } catch (\Exception $e) {
                $this->addFlash('error', 'Erreur pendant la suppression du projet : ' . $e->getMessage());
            }
        }

        return $this->redirectToRoute('app_project_index', [], Response::HTTP_SEE_OTHER);
    }
}

travail/mission/templates/project/_delete_form.html.twig
<form method="post" action="{{ path('app_project_delete', {'id': project.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ project.id) }}">
    <button class="btn">Delete</button>
</form>

travail/mission/templates/project/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="button button-submit mt-4">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

travail/mission/templates/project/_project_card.html.twig
<article class="card-project">
    <a href="{{ path('app_project_show', {'id': project.id}) }}">
        <h2>{% block project_title %}{% endblock %}</h2>
    </a>
    <div class="card-project-icons">
        <a href="{{ path('app_project_edit', {'id': project.id}) }}" data-turbo="false"><i class="fa-solid fa-pen"></i></a>
        <form method="post" action="{{ path('app_project_delete', {'id': project.id}) }}" style="display:inline">
            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ project.id) }}">
            <button
                type="submit"
                class="btn btn-link text-danger p-0 m-0 align-baseline"
                onclick="return confirm('Delete this project?');"
            >
                <i class="fa-solid fa-trash"></i>
            </button>
        </form>
    </div>
</article>

travail/mission/templates/project/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ project is null ? 'Nouveau Projet' : 'Modifier Projet' }} {% endblock %}

{% block header_title %} {{ project is null ? 'Nouveau Projet' : project.title }} {% endblock %}

{% block nav %}
    {% include 'nav.html.twig' with {'activeRoute': 'app_project_index'} %}
{% endblock %}

{% block content %}
    {{ include('project/_form.html.twig') }}
{% endblock %}

travail/mission/templates/project/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Project index{% endblock %}

{% block body %}
    <h1>Project index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>StartDate</th>
                <th>Deadline</th>
                <th>IsArchived</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for project in projects %}
            <tr>
                <td>{{ project.id }}</td>
                <td>{{ project.title }}</td>
                <td>{{ project.startDate ? project.startDate|date('Y-m-d') : '' }}</td>
                <td>{{ project.deadline ? project.deadline|date('Y-m-d') : '' }}</td>
                <td>{{ project.isArchived ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_project_show', {'id': project.id}) }}">show</a>
                    <a href="{{ path('app_project_edit', {'id': project.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_project_new') }}">Create new</a>
{% endblock %}

travail/mission/templates/project/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Projet{% endblock %}

{% block header_title %}Nouveau Projet{% endblock %}

{% block nav %}
    {% include 'nav.html.twig' with {'activeRoute': 'app_project_index'} %}
{% endblock %}

{% block content %}
    {{ include('project/_form.html.twig') }}
{% endblock %}

travail/mission/templates/project/projects.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Projets{% endblock %}

{% block nav %}
    {% include 'nav.html.twig' with {'activeRoute': 'app_project_index'} %}
{% endblock %}

{% block header_title %}Projets{% endblock %}

{% block content %}
    <div id="projects-container">
        {% for project in projects %}
            {% embed 'project/_project_card.html.twig' %}
                {% block project_title %}{{ project.title }}{% endblock %}
            {% endembed %}
        {% endfor %}
        <article class="card-project">
            <a href="{{ path('app_project_new') }}" data-turbo="false">
            <i class="fa-solid fa-circle-plus add-project-icon"></i>
            <h2>Ajouter un projet</h2>
            </a>
        </article>
    </div>
{% endblock %}

travail/mission/templates/project/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ project.title }}{% endblock %}

{% block nav %}
    {% include 'nav.html.twig' with {'activeRoute': 'app_project_index'} %}
{% endblock %}

{% block header %} 
    <div class="flex-header">
        <h1>{% block header_title %}{{ project.title }}{% endblock %}</h1>
        <div class="user-list">
            {% for user in project.users %}
                <div class="avatar">{{ user.initials }}</div>
            {% endfor %}
        </div>
        <a class="button" data-turbo="false" href="{{ path('app_project_edit', {'id': project.id}) }}">Modifier</a>
    </div>
{% endblock %}

{% block content %}
    <div id="tasks-container">
        {% for category in categories %}
            {% include 'task/_category_card.html.twig' with {'category': category, 'tasks': category.tasks} %}
        {% endfor %}
    </div>

{% endblock %}